#!/usr/bin/env python3
"""Generate frozen golden percentiles by executing the REFERENCE evaluator.

Provenance script — run once to produce
``backend/tests/fixtures/golden_scores.json``. Committed so the parity test
never needs the reference repo at runtime.

The reference evaluator (``/Users/Montrose/IPIP-NEO-PI/app/evaluator.py``)
exposes ``evaluate_api(request)`` which reads ``Sex``, ``Age`` and ``Q1..Q120``
off a bottle request and returns a JSON dict of ``{LABEL: percentile}`` for the
5 domains + 30 facets. We drive it directly with a fake request object and a
stubbed ``bottle`` module (the reference imports bottle only for its unused
``evaluate`` template path).

Reference response vector: the post-keying submitted values in
``IPIP-NEO-PI/app/tests/common.py`` (``sanswers``), identical to the two data
rows in ``app/tests/reference.dat``. These are SUBMITTED (post-keying) values,
so at parity time they feed our engine's ``score_prekeyed`` path directly.

To cover all 8 norm cells we score that one vector across every
(sex, representative age) combination.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import types
from pathlib import Path

REFERENCE_EVAL = Path("/Users/Montrose/IPIP-NEO-PI/app/evaluator.py")
OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "tests"
    / "fixtures"
    / "golden_scores.json"
)

# Post-keying submitted values (common.py `sanswers` == reference.dat rows).
SANSWERS = (
    "455454245414355144252442444444435454354214445435053442424254"
    "455453415314242354554251515543245452445414245444452135425154"
)

# One representative age per band (well inside each, so band edges are covered
# separately by unit tests) times both sexes -> all 8 norm cells.
AGE_BY_BAND = {"<21": 18, "21-40": 28, "41-60": 50, ">60": 70}


def _load_reference():
    """Import the reference evaluator with a stubbed ``bottle`` module."""
    bottle = types.ModuleType("bottle")
    bottle.template = lambda *a, **k: None  # unused by evaluate_api
    sys.modules["bottle"] = bottle
    spec = importlib.util.spec_from_file_location("ref_evaluator", REFERENCE_EVAL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class _FakeForms:
    def __init__(self, data: dict[str, str]):
        self._data = data

    def get(self, key, default=None):
        return self._data.get(key, default)


class _FakeRequest:
    def __init__(self, data: dict[str, str]):
        self.forms = _FakeForms(data)


def _run_reference(ref, sex_title: str, age: int, submitted: list[int]) -> dict:
    data = {"Sex": sex_title, "Age": str(age)}
    for i in range(1, 121):
        data[f"Q{i}"] = str(submitted[i - 1])
    return json.loads(ref.evaluate_api(_FakeRequest(data)))


def main() -> None:
    ref = _load_reference()
    submitted = [int(c) for c in SANSWERS]
    if len(submitted) != 120:
        raise SystemExit(f"expected 120 submitted values, got {len(submitted)}")

    cases = []
    for sex_title, sex_key in (("Male", "male"), ("Female", "female")):
        for band, age in AGE_BY_BAND.items():
            scores = _run_reference(ref, sex_title, age, submitted)
            cases.append(
                {
                    "sex": sex_key,
                    "age": age,
                    "band": band,
                    "scores": scores,  # {LABEL: percentile} — 5 domains + 30 facets
                }
            )

    fixture = {
        "provenance": (
            "Generated by scripts/gen_goldens.py from the reference "
            "evaluate_api in IPIP-NEO-PI/app/evaluator.py, using the post-keying "
            "sanswers vector from IPIP-NEO-PI/app/tests/common.py."
        ),
        "submitted_prekeying": False,  # these are POST-keying values
        "answers_submitted": submitted,
        "cases": cases,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(cases)} golden cases to {OUTPUT}")


if __name__ == "__main__":
    main()
